// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleCrudApp.Data;

#nullable disable

namespace SimpleCrudApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SimpleCrudApp.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Gpa")
                        .HasColumnType("float");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassName = "CNTT-K15A",
                            DateOfBirth = new DateTime(2003, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "an.nguyen@example.com",
                            FullName = "Nguyễn Văn An",
                            Gpa = 8.5,
                            StudentCode = "SV001"
                        },
                        new
                        {
                            Id = 2,
                            ClassName = "CNTT-K15B",
                            DateOfBirth = new DateTime(2003, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "binh.tran@example.com",
                            FullName = "Trần Thị Bình",
                            Gpa = 9.0,
                            StudentCode = "SV002"
                        },
                        new
                        {
                            Id = 3,
                            ClassName = "HTTT-K14",
                            DateOfBirth = new DateTime(2002, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cuong.le@example.com",
                            FullName = "Lê Hoàng Cường",
                            Gpa = 7.2000000000000002,
                            StudentCode = "SV003"
                        },
                        new
                        {
                            Id = 4,
                            ClassName = "CNTT-K16A",
                            DateOfBirth = new DateTime(2004, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dung.pham@example.com",
                            FullName = "Phạm Thu Dung",
                            Gpa = 6.7999999999999998,
                            StudentCode = "SV004"
                        },
                        new
                        {
                            Id = 5,
                            ClassName = "KTPM-K15",
                            DateOfBirth = new DateTime(2003, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "duc.vu@example.com",
                            FullName = "Vũ Minh Đức",
                            Gpa = 8.8000000000000007,
                            StudentCode = "SV005"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
